import crypto from 'node:crypto';
import { getStore } from '@netlify/blobs';

const STORE = getStore('saint-louis-data');
const VERSION = 'netlify-blobs-v4';
const TTL = 8 * 60 * 60 * 1000;
const MAX_IMAGE = 2 * 1024 * 1024;
const ADMIN_USER = process.env.ADMIN_USER || 'admin';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || '';
const DAYS = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];
const HOURS = Object.fromEntries(DAYS.map(day => [day, '']));
const BUSINESS = { whatsapp:'237699242376', phone:'699 24 23 76', address:'WG2M+HH2, Yaoundé, Cameroun', landmark:'Près de Neptune Oil · Chapelle Manguier', deliveryEnabled:true, pickupEnabled:true, deliveryFee:0, freeDeliveryFrom:0, paymentMethods:['Paiement à la livraison','Paiement au retrait en boutique'] };
const STATUSES = ['pending','confirmed','preparing','out_for_delivery','delivered','received','cancelled'];
const SEED = [
  ['Dictionnaire Larousse','Livres & dictionnaires','Dictionnaires et ouvrages de référence disponibles en librairie.',10,'/assets/dictionaries.jpg',true],
  ["Oxford Advanced Learner's Dictionary",'Livres & dictionnaires','Ouvrage de référence en langue anglaise.',8,'/assets/dictionaries.jpg',true],
  ['Manuels scolaires collège','Manuels scolaires','Sélection de manuels pour les classes du secondaire.',20,'/assets/school.jpg',true],
  ['Manuels primaire & CE2','Manuels scolaires','Livres et cahiers d’activités pour le primaire.',20,'/assets/school2.jpg',true],
  ['Bibles & livres religieux','Livres religieux','Différentes éditions et formats de Bibles.',12,'/assets/hero.jpg',true],
  ['Papeterie & fournitures','Papeterie','Stylos, cahiers, articles scolaires et de bureau.',30,'/assets/hero.jpg',false]
];
const json = (data, status=200, headers={}) => new Response(JSON.stringify(data), { status, headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers} });
const text = (data, status=200, headers={}) => new Response(data, { status, headers:{'Content-Type':'text/plain; charset=utf-8',...headers} });
const makeId = prefix => `${prefix}_${Date.now().toString(36)}_${crypto.randomBytes(5).toString('hex')}`;
const makeCode = () => `SL-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;
const number = (value, fallback=0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const cleanProduct = p => ({ id:p.id, name:p.name, category:p.category, description:p.description || '', price:p.price == null ? null : number(p.price), image:p.image || '/assets/hero.jpg', stock:Math.max(0,number(p.stock)), featured:Boolean(p.featured), active:p.active !== false });
async function get(key, fallback=null) { return (await STORE.get(key, {type:'json'})) ?? fallback; }
async function set(key, value, options={}) { return STORE.setJSON(key, value, options); }
async function list(prefix) { const {blobs=[]}=await STORE.list({prefix}); return Promise.all(blobs.map(blob => STORE.get(blob.key,{type:'json'}))); }
async function body(req) { const raw=await req.text(); if(!raw)return {}; try{return JSON.parse(raw);}catch{throw new Error('JSON invalide');} }
function cookies(req) { const result={}; for(const part of (req.headers.get('cookie')||'').split(';')) { const [key,...value]=part.trim().split('='); if(key) result[key]=decodeURIComponent(value.join('=')); } return result; }
function sessionCookie(token, secure, maxAge=TTL/1000) { return `sl_admin=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}${secure?'; Secure':''}`; }
async function initialize() {
  if ((await get('meta'))?.version === VERSION) return;
  const lock=await set('init-lock',{at:Date.now()},{onlyIfNew:true});
  if(!lock.modified){for(let i=0;i<10;i++){if((await get('meta'))?.version===VERSION)return;await new Promise(resolve=>setTimeout(resolve,100));}}
  const existing=(await list('product:')).filter(Boolean);
  if(!existing.length){ for(const [name,category,description,stock,image,featured] of SEED){ const product={id:makeId('p'),name,category,description,price:null,image,stock,featured,active:true,created_at:new Date().toISOString()}; await set(`product:${product.id}`,product); } }
  if(!(await get('settings:business')))await set('settings:business',BUSINESS);
  if(!(await get('settings:hours')))await set('settings:hours',HOURS);
  for(const order of (await list('order:')).filter(Boolean)) if(order.code&&order.id) await set(`order-code:${order.code}`,{id:order.id});
  await set('meta',{version:VERSION,initializedAt:new Date().toISOString()});
  await STORE.delete('init-lock');
}
async function admin(req){const token=cookies(req).sl_admin;if(!token)return null;const value=await get(`session:${token}`);if(!value||Date.now()-value.createdAt>TTL){if(value)await STORE.delete(`session:${token}`);return null;}return {username:value.username||ADMIN_USER};}
const unauthorized=()=>json({error:'Connexion gérant requise.'},401);
async function products(includeHidden=false){return (await list('product:')).filter(Boolean).filter(p=>includeHidden||p.active!==false).sort((a,b)=>Number(b.featured)-Number(a.featured)||String(b.created_at).localeCompare(String(a.created_at))).map(cleanProduct);}
async function findOrder(code){const normalized=String(code||'').trim().toUpperCase();if(!normalized)return null;const index=await get(`order-code:${normalized}`);if(index?.id){const order=await get(`order:${index.id}`);if(order)return order;}const order=(await list('order:')).find(item=>item?.code===normalized)||null;if(order)await set(`order-code:${normalized}`,{id:order.id});return order;}
async function stock(id,delta){for(let attempt=0;attempt<5;attempt++){const key=`product:${id}`,found=await STORE.getWithMetadata(key,{type:'json'});if(!found?.data)throw new Error('Produit introuvable.');const product=found.data,next=number(product.stock)+delta;if(next<0)throw new Error(`Stock insuffisant pour ${product.name}.`);product.stock=next;const result=await set(key,product,{onlyIfMatch:found.etag});if(result.modified)return product;}throw new Error('Le stock a été modifié simultanément. Réessayez.');}
async function image(value,previous=''){const raw=String(value||'');if(!raw.startsWith('data:'))return raw||'/assets/hero.jpg';const match=raw.match(/^data:(image\/[\w.+-]+);base64,([A-Za-z0-9+/=\s]+)$/);if(!match)throw new Error("Format d'image non pris en charge.");const data=match[2].replace(/\s/g,''),buffer=Buffer.from(data,'base64');if(!buffer.length||buffer.length>MAX_IMAGE)throw new Error("Image invalide ou trop lourde (2 Mo maximum).");const imageId=makeId('img');await set(`image:${imageId}`,{contentType:match[1],data,created_at:new Date().toISOString()});if(/^\/api\/images\/[^/]+$/.test(previous))await STORE.delete(`image:${previous.split('/').pop()}`).catch(()=>{});return `/api/images/${imageId}`;}
function publicOrder(o){return {code:o.code,customer_name:o.customer_name,status:o.status,fulfillment:o.fulfillment,payment_method:o.payment_method,subtotal:o.subtotal,delivery_fee:o.delivery_fee,total:o.total,received:Boolean(o.received),created_at:o.created_at,updated_at:o.updated_at,items:(o.items||[]).map(i=>({name:i.name,quantity:i.quantity,unit_price:i.unit_price==null?null:number(i.unit_price)}))};}
function hash(password){const salt=crypto.randomBytes(16).toString('hex');return new Promise((resolve,reject)=>crypto.scrypt(String(password),salt,64,(error,value)=>error?reject(error):resolve(`${salt}:${value.toString('hex')}`)));}
async function matches(password,saved){if(!saved){if(!ADMIN_PASSWORD)return false;const a=Buffer.from(String(password)),b=Buffer.from(ADMIN_PASSWORD);return a.length===b.length&&crypto.timingSafeEqual(a,b);}try{const [salt,expected]=String(saved).split(':');const derived=await new Promise((resolve,reject)=>crypto.scrypt(String(password),salt,64,(error,value)=>error?reject(error):resolve(value)));const target=Buffer.from(expected,'hex');return derived.length===target.length&&crypto.timingSafeEqual(derived,target);}catch{return false;}}

export default async function handler(req){
  try{
    const url=new URL(req.url),path=url.pathname,secure=url.protocol==='https:';
    if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':url.origin,'Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'}});
    await initialize();
    if(path==='/api/health'&&req.method==='GET')return json({ok:true,service:'saint-louis-netlify',version:VERSION,admin_password_configured:Boolean(ADMIN_PASSWORD)||Boolean(await get('admin:password'))});
    const im=path.match(/^\/api\/images\/([^/]+)$/);if(im&&req.method==='GET'){const value=await get(`image:${im[1]}`);if(!value?.data)return json({error:'Image introuvable.'},404);return new Response(Buffer.from(value.data,'base64'),{headers:{'Content-Type':value.contentType||'image/jpeg','Cache-Control':'public, max-age=31536000, immutable'}});}
    if(path==='/api/auth/login'&&req.method==='POST'){const b=await body(req),saved=await get('admin:password');if(!saved&&!ADMIN_PASSWORD)return json({error:'ADMIN_PASSWORD doit être configuré sur Netlify.'},503);if(String(b.username||'').trim()!==ADMIN_USER||!(await matches(b.password||'',saved)))return json({error:'Identifiants incorrects.'},401);const token=crypto.randomBytes(32).toString('hex');await set(`session:${token}`,{createdAt:Date.now(),username:ADMIN_USER});return json({ok:true,user:{username:ADMIN_USER}},200,{'Set-Cookie':sessionCookie(token,secure)});}
    if(path==='/api/auth/me'&&req.method==='GET'){const user=await admin(req);return json({authenticated:Boolean(user),user});}
    if(path==='/api/auth/logout'&&req.method==='POST'){const token=cookies(req).sl_admin;if(token)await STORE.delete(`session:${token}`);return json({ok:true},200,{'Set-Cookie':sessionCookie('',secure,0)});}
    if(path==='/api/settings/business'&&req.method==='GET')return json({...BUSINESS,...(await get('settings:business',{}))});
    if(path==='/api/settings/hours'&&req.method==='GET')return json({...HOURS,...(await get('settings:hours',{}))});
    if(path==='/api/products'&&req.method==='GET'){let result=await products();const query=(url.searchParams.get('q')||'').toLowerCase(),category=url.searchParams.get('category')||'';if(query)result=result.filter(p=>[p.name,p.category,p.description].some(value=>String(value).toLowerCase().includes(query)));if(category)result=result.filter(p=>p.category===category);return json(result);}
    if(path==='/api/products/categories'&&req.method==='GET')return json([...new Set((await products()).map(p=>p.category))].sort((a,b)=>a.localeCompare(b,'fr')));
    if(path==='/api/orders'&&req.method==='POST'){const b=await body(req),business={...BUSINESS,...(await get('settings:business',{}))},fulfillment=b.fulfillment==='pickup'?'pickup':'delivery';if(!String(b.customer_name||'').trim()||!String(b.phone||'').trim())return json({error:'Nom et téléphone requis.'},400);if(!Array.isArray(b.items)||!b.items.length)return json({error:'Votre panier est vide.'},400);if(fulfillment==='delivery'&&!business.deliveryEnabled)return json({error:'La livraison est indisponible.'},400);if(fulfillment==='pickup'&&!business.pickupEnabled)return json({error:'Le retrait est indisponible.'},400);if(fulfillment==='delivery'&&!String(b.address||'').trim())return json({error:'Adresse de livraison requise.'},400);const normalized=[];let subtotal=0;for(const item of b.items){const p=await get(`product:${String(item.id)}`),quantity=Math.max(1,Math.min(999,Math.floor(number(item.quantity,1))));if(!p||p.active===false)continue;if(quantity>number(p.stock))return json({error:`Stock insuffisant pour ${p.name}.`},400);const unit=p.price==null?null:number(p.price);if(unit!=null)subtotal+=unit*quantity;normalized.push({id:p.id,name:p.name,quantity,unit_price:unit});}if(!normalized.length)return json({error:'Aucun produit valide dans le panier.'},400);const free=number(business.freeDeliveryFrom)>0&&subtotal>=number(business.freeDeliveryFrom),delivery_fee=fulfillment==='delivery'&&!free?Math.max(0,number(business.deliveryFee)):0,order={id:makeId('o'),code:makeCode(),customer_name:String(b.customer_name).trim().slice(0,120),phone:String(b.phone).trim().slice(0,40),email:String(b.email||'').trim().slice(0,160),address:fulfillment==='pickup'?'Retrait en boutique':String(b.address).trim().slice(0,400),notes:String(b.notes||'').trim().slice(0,600),subtotal,delivery_fee,total:subtotal+delivery_fee,status:'pending',received:false,fulfillment,payment_method:business.paymentMethods.includes(b.payment_method)?b.payment_method:business.paymentMethods[0],items:normalized,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};const changed=[];try{for(const item of normalized){await stock(item.id,-item.quantity);changed.push(item);}await set(`order:${order.id}`,order);await set(`order-code:${order.code}`,{id:order.id});}catch(error){for(const item of changed)await stock(item.id,item.quantity).catch(()=>{});return json({error:error.message},400);}return json({id:order.id,code:order.code,total:order.total,delivery_fee,fulfillment,price_pending:normalized.some(item=>item.unit_price==null),status:'pending',message:'Commande enregistrée.',whatsapp:business.whatsapp},201);}
    const om=path.match(/^\/api\/orders\/([^/]+)$/);if(om&&req.method==='GET'){const o=await findOrder(om[1]);return o?json(publicOrder(o)):json({error:'Commande introuvable.'},404);}
    const rm=path.match(/^\/api\/orders\/([^/]+)\/received$/);if(rm&&req.method==='POST'){const o=await findOrder(rm[1]);if(!o)return json({error:'Commande introuvable.'},404);if(o.status!=='delivered'&&o.status!=='received')return json({error:'Cette commande ne peut pas encore être confirmée.'},409);o.status='received';o.received=true;o.updated_at=new Date().toISOString();await set(`order:${o.id}`,o);return json({ok:true,status:'received'});}
    const user=await admin(req);if(path==='/api/admin/products'&&req.method==='GET'){if(!user)return unauthorized();return json(await products(true));}if(path==='/api/admin/orders'&&req.method==='GET'){if(!user)return unauthorized();return json((await list('order:')).filter(Boolean).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))));}
    if(path==='/api/admin/settings/business'&&req.method==='PUT'){if(!user)return unauthorized();const b=await body(req),value={...BUSINESS,...(await get('settings:business',{}))};for(const key of ['whatsapp','phone','address','landmark'])if(typeof b[key]==='string')value[key]=b[key].trim();value.deliveryEnabled=Boolean(b.deliveryEnabled);value.pickupEnabled=Boolean(b.pickupEnabled);value.deliveryFee=Math.max(0,number(b.deliveryFee));value.freeDeliveryFrom=Math.max(0,number(b.freeDeliveryFrom));value.paymentMethods=Array.isArray(b.paymentMethods)&&b.paymentMethods.length?b.paymentMethods.map(String).slice(0,10):BUSINESS.paymentMethods;if(!value.deliveryEnabled&&!value.pickupEnabled)return json({error:'Activez la livraison ou le retrait.'},400);await set('settings:business',value);return json(value);}
    if(path==='/api/admin/settings/hours'&&req.method==='PUT'){if(!user)return unauthorized();const b=await body(req),value={};for(const key of DAYS)value[key]=typeof b[key]==='string'?b[key].trim().slice(0,60):'';await set('settings:hours',value);return json(value);}
    if(path==='/api/admin/security/password'&&req.method==='PUT'){if(!user)return unauthorized();const b=await body(req),saved=await get('admin:password');if(!b.currentPassword||!(await matches(b.currentPassword,saved)))return json({error:'Mot de passe actuel incorrect.'},400);if(String(b.newPassword||'').length<10||b.newPassword===b.currentPassword)return json({error:'Nouveau mot de passe invalide.'},400);await set('admin:password',await hash(b.newPassword));return json({ok:true});}
    if(path==='/api/products'&&req.method==='POST'){if(!user)return unauthorized();const b=await body(req);if(!String(b.name||'').trim()||!String(b.category||'').trim())return json({error:'Nom et catégorie requis.'},400);const p={id:makeId('p'),name:String(b.name).trim(),category:String(b.category).trim(),description:String(b.description||'').trim(),price:b.price===''||b.price==null?null:Math.max(0,number(b.price)),image:await image(b.image),stock:Math.max(0,Math.floor(number(b.stock))),featured:Boolean(b.featured),active:true,created_at:new Date().toISOString()};await set(`product:${p.id}`,p);return json(cleanProduct(p),201);}
    const pm=path.match(/^\/api\/products\/([^/]+)$/);if(pm&&(req.method==='PUT'||req.method==='DELETE')){if(!user)return unauthorized();const key=`product:${pm[1]}`,old=await get(key);if(!old)return json({error:'Produit introuvable.'},404);if(req.method==='DELETE'){old.active=false;old.updated_at=new Date().toISOString();await set(key,old);return json({ok:true});}const b=await body(req),p={...old,name:String(b.name??old.name).trim(),category:String(b.category??old.category).trim(),description:String(b.description??old.description??'').trim(),price:b.price===''||b.price==null?null:Math.max(0,number(b.price)),image:b.image?await image(b.image,old.image):old.image,stock:Math.max(0,Math.floor(number(b.stock,old.stock))),featured:Boolean(b.featured),active:b.active!==false,updated_at:new Date().toISOString()};await set(key,p);return json(cleanProduct(p));}
    const sm=path.match(/^\/api\/admin\/orders\/([^/]+)\/status$/);if(sm&&req.method==='PUT'){if(!user)return unauthorized();const b=await body(req);if(!STATUSES.includes(b.status))return json({error:'Statut invalide.'},400);const key=`order:${sm[1]}`,o=await get(key);if(!o)return json({error:'Commande introuvable.'},404);if(b.status==='cancelled'&&!o.stock_restored){for(const item of o.items||[])await stock(item.id,item.quantity).catch(()=>{});o.stock_restored=true;}o.status=b.status;o.received=b.status==='received';o.updated_at=new Date().toISOString();await set(key,o);return json({ok:true,status:o.status});}
    if(path==='/api/admin/backup'&&req.method==='GET'){if(!user)return unauthorized();return new Response(JSON.stringify({exported_at:new Date().toISOString(),format:'saint-louis-netlify-backup-v4',settings:{business:await get('settings:business',BUSINESS),hours:await get('settings:hours',HOURS)},products:(await list('product:')).filter(Boolean),orders:(await list('order:')).filter(Boolean)},null,2),{headers:{'Content-Type':'application/json; charset=utf-8','Content-Disposition':`attachment; filename="saint-louis-backup-${new Date().toISOString().slice(0,10)}.json`}});}
    const base=(process.env.SITE_URL||process.env.URL||`${url.protocol}//${url.host}`).replace(/\/$/,'');if(path==='/robots.txt')return text(`User-agent: *\nAllow: /\nDisallow: /admin.html\nSitemap: ${base}/sitemap.xml\n`);if(path==='/sitemap.xml')return new Response(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/catalogue.html','/panier.html','/commande.html','/suivi.html'].map(page=>`<url><loc>${base}${page}</loc></url>`).join('')}</urlset>`,{headers:{'Content-Type':'application/xml; charset=utf-8'}});return json({error:'API introuvable.'},404);
  }catch(error){console.error(error);return json({error:error.message==='JSON invalide'?'Requête invalide.':'Une erreur interne est survenue.'},error.message==='JSON invalide'?400:500);}
}
export const config={path:['/api/*','/robots.txt','/sitemap.xml']};
