import crypto from 'node:crypto';
import { getStore } from '@netlify/blobs';

const STORE_NAME = 'saint-louis-data';
const STORE_VERSION = 'netlify-blobs-v3';
const SESSION_TTL_MS = 8 * 60 * 60 * 1000;
const MAX_IMAGE_BYTES = 2 * 1024 * 1024;
const MIN_PASSWORD_LENGTH = 10;
const ADMIN_USER = process.env.ADMIN_USER || 'admin';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || '';
const store = getStore(STORE_NAME);

const DEFAULT_HOURS = Object.fromEntries(['monday','tuesday','wednesday','thursday','friday','saturday','sunday'].map(day => [day, '']));
const DEFAULT_BUSINESS = {
  whatsapp: '237699242376', phone: '699 24 23 76', address: 'WG2M+HH2, Yaoundé, Cameroun',
  landmark: 'Près de Neptune Oil · Chapelle Manguier', deliveryEnabled: true, pickupEnabled: true,
  deliveryFee: 0, freeDeliveryFrom: 0, paymentMethods: ['Paiement à la livraison', 'Paiement au retrait en boutique']
};
const STATUSES = ['pending','confirmed','preparing','out_for_delivery','delivered','received','cancelled'];
const SEED = [
  ['Dictionnaire Larousse','Livres & dictionnaires','Dictionnaires et ouvrages de référence disponibles en librairie.',10,'/assets/dictionaries.jpg',1],
  ["Oxford Advanced Learner's Dictionary",'Livres & dictionnaires','Ouvrage de référence en langue anglaise.',8,'/assets/dictionaries.jpg',1],
  ['Manuels scolaires collège','Manuels scolaires','Sélection de manuels pour les classes du secondaire.',20,'/assets/school.jpg',1],
  ['Manuels primaire & CE2','Manuels scolaires','Livres et cahiers d’activités pour le primaire.',20,'/assets/school2.jpg',1],
  ['Bibles & livres religieux','Livres religieux','Différentes éditions et formats de Bibles.',12,'/assets/hero.jpg',1],
  ['Papeterie & fournitures','Papeterie','Stylos, cahiers, articles scolaires et de bureau.',30,'/assets/hero.jpg',0]
];

const json = (data, status = 200, headers = {}) => new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', ...headers } });
const text = (data, status = 200, headers = {}) => new Response(data, { status, headers: { 'Content-Type': 'text/plain; charset=utf-8', ...headers } });
const id = prefix => `${prefix}_${Date.now().toString(36)}_${crypto.randomBytes(5).toString('hex')}`;
const orderCode = () => `SL-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;
const cleanProduct = p => ({ id:p.id, name:p.name, category:p.category, description:p.description || '', price:p.price == null ? null : Number(p.price), image:p.image || '/assets/hero.jpg', stock:Number(p.stock || 0), featured:Boolean(p.featured), active:p.active !== false });

async function getJSON(key, fallback = null) { return (await store.get(key, { type:'json' })) ?? fallback; }
async function setJSON(key, value, options = {}) { return store.setJSON(key, value, options); }
async function listJSON(prefix) { const { blobs = [] } = await store.list({ prefix }); return Promise.all(blobs.map(blob => store.get(blob.key, { type:'json' }))); }
async function readBody(req) { const raw = await req.text(); if (!raw) return {}; try { return JSON.parse(raw); } catch { throw new Error('JSON invalide'); } }
function cookies(req) { const result = {}; for (const part of (req.headers.get('cookie') || '').split(';')) { const [key, ...value] = part.trim().split('='); if (key) result[key] = decodeURIComponent(value.join('=')); } return result; }
function cookie(token, secure, maxAge = SESSION_TTL_MS / 1000) { return `sl_admin=${encodeURIComponent(token)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}${secure ? '; Secure' : ''}`; }
function safeNumber(value, fallback = 0) { const number = Number(value); return Number.isFinite(number) ? number : fallback; }

async function initialize() {
  if ((await getJSON('meta'))?.version === STORE_VERSION) return;
  const lock = await setJSON('init-lock', { at: Date.now() }, { onlyIfNew:true });
  if (!lock.modified) { for (let i=0; i<10; i++) { if ((await getJSON('meta'))?.version === STORE_VERSION) return; await new Promise(resolve => setTimeout(resolve, 100)); } }
  if (!(await listJSON('product:')).filter(Boolean).length) {
    for (const [name, category, description, stock, image, featured] of SEED) await setJSON(`product:${id('p')}`, { id:id('p'), name, category, description, price:null, image, stock, featured:Boolean(featured), active:true, created_at:new Date().toISOString() });
  }
  if (!(await getJSON('settings:business'))) await setJSON('settings:business', DEFAULT_BUSINESS);
  if (!(await getJSON('settings:hours'))) await setJSON('settings:hours', DEFAULT_HOURS);
  await setJSON('meta', { version:STORE_VERSION, initializedAt:new Date().toISOString() });
  await store.delete('init-lock');
}
async function currentSession(req) { const token = cookies(req).sl_admin; if (!token) return null; const session = await getJSON(`session:${token}`); if (!session || Date.now() - session.createdAt > SESSION_TTL_MS) { if (session) await store.delete(`session:${token}`); return null; } return { username:session.username || ADMIN_USER }; }
const unauthorized = () => json({ error:'Connexion gérant requise.' }, 401);
async function products(includeHidden = false) { return (await listJSON('product:')).filter(Boolean).filter(p => includeHidden || p.active !== false).sort((a,b) => Number(b.featured)-Number(a.featured) || String(b.created_at).localeCompare(String(a.created_at))).map(cleanProduct); }
async function findOrder(code) { const normalized = String(code || '').trim().toUpperCase(); if (!normalized) return null; const index = await getJSON(`order-code:${normalized}`); if (index?.id) { const order = await getJSON(`order:${index.id}`); if (order) return order; } const order = (await listJSON('order:')).find(item => item?.code === normalized) || null; if (order) await setJSON(`order-code:${normalized}`, { id:order.id }); return order; }
async function updateStock(productId, delta) { for (let attempt=0; attempt<5; attempt++) { const key=`product:${productId}`; const found=await store.getWithMetadata(key,{type:'json'}); if (!found?.data) throw new Error('Produit introuvable.'); const product=found.data; const next=safeNumber(product.stock)+delta; if (next<0) throw new Error(`Stock insuffisant pour ${product.name}.`); product.stock=next; const result=await setJSON(key,product,{onlyIfMatch:found.etag}); if (result.modified) return product; } throw new Error('Le stock a été modifié simultanément. Réessayez.'); }
async function saveImage(value, previous = '') { const raw=String(value || ''); if (!raw.startsWith('data:')) return raw || '/assets/hero.jpg'; const match=raw.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,([A-Za-z0-9+/=\s]+)$/); if (!match) throw new Error("Format d'image non pris en charge."); const data=match[2].replace(/\s/g,''); const buffer=Buffer.from(data,'base64'); if (!buffer.length || buffer.length > MAX_IMAGE_BYTES) throw new Error("Image invalide ou trop lourde (2 Mo maximum)."); const imageId=id('img'); await setJSON(`image:${imageId}`,{contentType:match[1],data,created_at:new Date().toISOString()}); if (/^\/api\/images\/[^/]+$/.test(previous)) await store.delete(`image:${previous.split('/').pop()}`).catch(()=>{}); return `/api/images/${imageId}`; }
function publicOrder(order) { return { code:order.code, customer_name:order.customer_name, status:order.status, fulfillment:order.fulfillment, payment_method:order.payment_method, subtotal:order.subtotal, delivery_fee:order.delivery_fee, total:order.total, received:Boolean(order.received), created_at:order.created_at, updated_at:order.updated_at, items:(order.items || []).map(item => ({ name:item.name, quantity:item.quantity, unit_price:item.unit_price == null ? null : Number(item.unit_price) })) }; }
function passwordHash(input) { const salt=crypto.randomBytes(16).toString('hex'); return new Promise((resolve,reject) => crypto.scrypt(String(input),salt,64,(error,buffer) => error ? reject(error) : resolve(`${salt}:${buffer.toString('hex')}`))); }
async function passwordMatches(input, saved) { if (!saved) { if (!ADMIN_PASSWORD) return false; const a=Buffer.from(String(input)), b=Buffer.from(ADMIN_PASSWORD); return a.length === b.length && crypto.timingSafeEqual(a,b); } try { const [salt,hash]=String(saved).split(':'); const derived=await new Promise((resolve,reject)=>crypto.scrypt(String(input),salt,64,(error,buffer)=>error?reject(error):resolve(buffer))); const expected=Buffer.from(hash,'hex'); return derived.length === expected.length && crypto.timingSafeEqual(derived,expected); } catch { return false; } }

export default async function handler(req) {
  try {
    const url=new URL(req.url), path=url.pathname, secure=url.protocol === 'https:';
    if (req.method === 'OPTIONS') return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':url.origin,'Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'}});
    await initialize();
    if (path === '/api/health' && req.method === 'GET') return json({ok:true,service:'saint-louis-netlify',version:STORE_VERSION,admin_password_configured:Boolean(ADMIN_PASSWORD) || Boolean(await getJSON('admin:password'))});
    const imageMatch=path.match(/^\/api\/images\/([^/]+)$/); if (imageMatch && req.method === 'GET') { const image=await getJSON(`image:${imageMatch[1]}`); if (!image?.data) return json({error:'Image introuvable.'},404); return new Response(Buffer.from(image.data,'base64'),{headers:{'Content-Type':image.contentType || 'image/jpeg','Cache-Control':'public, max-age=31536000, immutable'}}); }
    if (path === '/api/auth/login' && req.method === 'POST') { const body=await readBody(req), saved=await getJSON('admin:password'); if (!saved && !ADMIN_PASSWORD) return json({error:"ADMIN_PASSWORD doit être configuré sur Netlify."},503); if (String(body.username || '').trim() !== ADMIN_USER || !(await passwordMatches(body.password || '',saved))) return json({error:'Identifiants incorrects.'},401); const token=crypto.randomBytes(32).toString('hex'); await setJSON(`session:${token}`,{createdAt:Date.now(),username:ADMIN_USER}); return json({ok:true,user:{username:ADMIN_USER}},200,{'Set-Cookie':cookie(token,secure)}); }
    if (path === '/api/auth/me' && req.method === 'GET') { const user=await currentSession(req); return json({authenticated:Boolean(user),user}); }
    if (path === '/api/auth/logout' && req.method === 'POST') { const token=cookies(req).sl_admin; if (token) await store.delete(`session:${token}`); return json({ok:true},200,{'Set-Cookie':cookie('',secure,0)}); }
    if (path === '/api/settings/business' && req.method === 'GET') return json({...DEFAULT_BUSINESS,...(await getJSON('settings:business',{}))});
    if (path === '/api/settings/hours' && req.method === 'GET') return json({...DEFAULT_HOURS,...(await getJSON('settings:hours',{}))});
    if (path === '/api/products' && req.method === 'GET') { let list=await products(); const query=(url.searchParams.get('q')||'').toLowerCase(), category=url.searchParams.get('category')||''; if(query) list=list.filter(p=>[p.name,p.category,p.description].some(value=>String(value).toLowerCase().includes(query))); if(category) list=list.filter(p=>p.category===category); return json(list); }
    if (path === '/api/products/categories' && req.method === 'GET') return json([...new Set((await products()).map(p=>p.category))].sort((a,b)=>a.localeCompare(b,'fr')));
    if (path === '/api/orders' && req.method === 'POST') { const body=await readBody(req), business={...DEFAULT_BUSINESS,...(await getJSON('settings:business',{}))}, fulfillment=body.fulfillment === 'pickup' ? 'pickup' : 'delivery'; if(!String(body.customer_name||'').trim() || !String(body.phone||'').trim()) return json({error:'Nom et téléphone requis.'},400); if(!Array.isArray(body.items)||!body.items.length) return json({error:'Votre panier est vide.'},400); if(fulfillment==='delivery'&&!business.deliveryEnabled) return json({error:'La livraison est indisponible.'},400); if(fulfillment==='pickup'&&!business.pickupEnabled) return json({error:'Le retrait est indisponible.'},400); if(fulfillment==='delivery'&&!String(body.address||'').trim()) return json({error:'Adresse de livraison requise.'},400); const normalized=[]; let subtotal=0; for(const item of body.items){const product=await getJSON(`product:${String(item.id)}`); const quantity=Math.max(1,Math.min(999,Math.floor(safeNumber(item.quantity,1)))); if(!product||product.active===false) continue; if(quantity>safeNumber(product.stock)) return json({error:`Stock insuffisant pour ${product.name}.`},400); const unit=product.price==null?null:safeNumber(product.price); if(unit!=null) subtotal+=unit*quantity; normalized.push({id:product.id,name:product.name,quantity,unit_price:unit});} if(!normalized.length)return json({error:'Aucun produit valide dans le panier.'},400); const free=Number(business.freeDeliveryFrom)>0&&subtotal>=Number(business.freeDeliveryFrom), delivery_fee=fulfillment==='delivery'&&!free?Math.max(0,safeNumber(business.deliveryFee)):0; const order={id:id('o'),code:orderCode(),customer_name:String(body.customer_name).trim().slice(0,120),phone:String(body.phone).trim().slice(0,40),email:String(body.email||'').trim().slice(0,160),address:fulfillment==='pickup'?'Retrait en boutique':String(body.address).trim().slice(0,400),notes:String(body.notes||'').trim().slice(0,600),subtotal,delivery_fee,total:subtotal+delivery_fee,status:'pending',received:false,fulfillment,payment_method:business.paymentMethods.includes(body.payment_method)?body.payment_method:business.paymentMethods[0],items:normalized,created_at:new Date().toISOString(),updated_at:new Date().toISOString()}; const changed=[]; try { for(const item of normalized){await updateStock(item.id,-item.quantity);changed.push(item);} await setJSON(`order:${order.id}`,order); await setJSON(`order-code:${order.code}`,{id:order.id}); } catch(error) { for(const item of changed) await updateStock(item.id,item.quantity).catch(()=>{}); return json({error:error.message},400); } return json({id:order.id,code:order.code,total:order.total,delivery_fee,fulfillment,price_pending:normalized.some(item=>item.unit_price==null),status:order.status,message:'Commande enregistrée.',whatsapp:business.whatsapp},201); }
    const orderMatch=path.match(/^\/api\/orders\/([^/]+)$/); if(orderMatch&&req.method==='GET'){const order=await findOrder(orderMatch[1]);return order?json(publicOrder(order)):json({error:'Commande introuvable.'},404);}
    const receivedMatch=path.match(/^\/api\/orders\/([^/]+)\/received$/); if(receivedMatch&&req.method==='POST'){const order=await findOrder(receivedMatch[1]);if(!order)return json({error:'Commande introuvable.'},404);if(order.status!=='delivered'&&order.status!=='received')return json({error:'Cette commande ne peut pas encore être confirmée.'},409);order.status='received';order.received=true;order.updated_at=new Date().toISOString();await setJSON(`order:${order.id}`,order);return json({ok:true,status:'received'});}
    const user=await currentSession(req);
    if(path==='/api/admin/products'&&req.method==='GET'){if(!user)return unauthorized();return json(await products(true));}
    if(path==='/api/admin/orders'&&req.method==='GET'){if(!user)return unauthorized();return json((await listJSON('order:')).filter(Boolean).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))));}
    if(path==='/api/admin/settings/business'&&req.method==='PUT'){if(!user)return unauthorized();const body=await readBody(req), current={...DEFAULT_BUSINESS,...(await getJSON('settings:business',{}))};for(const key of ['whatsapp','phone','address','landmark'])if(typeof body[key]==='string')current[key]=body[key].trim();current.deliveryEnabled=Boolean(body.deliveryEnabled);current.pickupEnabled=Boolean(body.pickupEnabled);current.deliveryFee=Math.max(0,safeNumber(body.deliveryFee));current.freeDeliveryFrom=Math.max(0,safeNumber(body.freeDeliveryFrom));current.paymentMethods=Array.isArray(body.paymentMethods)&&body.paymentMethods.length?body.paymentMethods.map(String).slice(0,10):DEFAULT_BUSINESS.paymentMethods;if(!current.deliveryEnabled&&!current.pickupEnabled)return json({error:'Activez la livraison ou le retrait.'},400);await setJSON('settings:business',current);return json(current);}
    if(path==='/api/admin/settings/hours'&&req.method==='PUT'){if(!user)return unauthorized();const body=await readBody(req),hours={};for(const key of Object.keys(DEFAULT_HOURS))hours[key]=typeof body[key]==='string'?body[key].trim().slice(0,60):'';await setJSON('settings:hours',hours);return json(hours);}
    if(path==='/api/admin/security/password'&&req.method==='PUT'){if(!user)return unauthorized();const body=await readBody(req),saved=await getJSON('admin:password');if(!body.currentPassword||!(await passwordMatches(body.currentPassword,saved)))return json({error:'Mot de passe actuel incorrect.'},400);if(String(body.newPassword||'').length<MIN_PASSWORD_LENGTH||body.newPassword===body.currentPassword)return json({error:'Nouveau mot de passe invalide.'},400);await setJSON('admin:password',await passwordHash(body.newPassword));return json({ok:true});}
    if(path==='/api/products'&&req.method==='POST'){if(!user)return unauthorized();const body=await readBody(req);if(!String(body.name||'').trim()||!String(body.category||'').trim())return json({error:'Nom et catégorie requis.'},400);const product={id:id('p'),name:String(body.name).trim(),category:String(body.category).trim(),description:String(body.description||'').trim(),price:body.price===''||body.price==null?null:Math.max(0,safeNumber(body.price)),image:await saveImage(body.image),stock:Math.max(0,Math.floor(safeNumber(body.stock))),featured:Boolean(body.featured),active:true,created_at:new Date().toISOString()};await setJSON(`product:${product.id}`,product);return json(cleanProduct(product),201);}
    const productMatch=path.match(/^\/api\/products\/([^/]+)$/); if(productMatch&&(req.method==='PUT'||req.method==='DELETE')){if(!user)return unauthorized();const key=`product:${productMatch[1]}`,found=await getJSON(key);if(!found)return json({error:'Produit introuvable.'},404);if(req.method==='DELETE'){found.active=false;found.updated_at=new Date().toISOString();await setJSON(key,found);return json({ok:true});}const body=await readBody(req),product={...found,name:String(body.name??found.name).trim(),category:String(body.category??found.category).trim(),description:String(body.description??found.description??'').trim(),price:body.price===''||body.price==null?null:Math.max(0,safeNumber(body.price)),image:body.image?await saveImage(body.image,found.image):found.image,stock:Math.max(0,Math.floor(safeNumber(body.stock,found.stock))),featured:Boolean(body.featured),active:body.active!==false,updated_at:new Date().toISOString()};await setJSON(key,product);return json(cleanProduct(product));}
    const statusMatch=path.match(/^\/api\/admin\/orders\/([^/]+)\/status$/); if(statusMatch&&req.method==='PUT'){if(!user)return unauthorized();const body=await readBody(req);if(!STATUSES.includes(body.status))return json({error:'Statut invalide.'},400);const key=`order:${statusMatch[1]}`,order=await getJSON(key);if(!order)return json({error:'Commande introuvable.'},404);if(body.status==='cancelled'&&!order.stock_restored){for(const item of order.items||[])await updateStock(item.id,item.quantity).catch(()=>{});order.stock_restored=true;}order.status=body.status;order.received=body.status==='received';order.updated_at=new Date().toISOString();await setJSON(key,order);return json({ok:true,status:order.status});}
    if(path==='/api/admin/backup'&&req.method==='GET'){if(!user)return unauthorized();return new Response(JSON.stringify({exported_at:new Date().toISOString(),format:'saint-louis-netlify-backup-v3',settings:{business:await getJSON('settings:business',DEFAULT_BUSINESS),hours:await getJSON('settings:hours',DEFAULT_HOURS)},products:(await listJSON('product:')).filter(Boolean),orders:(await listJSON('order:')).filter(Boolean)},null,2),{headers:{'Content-Type':'application/json','Content-Disposition':`attachment; filename="saint-louis-backup-${new Date().toISOString().slice(0,10)}.json`}});}
    const base=(process.env.SITE_URL||process.env.URL||`${url.protocol}//${url.host}`).replace(/\/$/,''); if(path==='/robots.txt')return text(`User-agent: *\nAllow: /\nDisallow: /admin.html\nSitemap: ${base}/sitemap.xml\n`); if(path==='/sitemap.xml')return new Response(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/catalogue.html','/panier.html','/commande.html','/suivi.html'].map(page=>`<url><loc>${base}${page}</loc></url>`).join('')}</urlset>`,{headers:{'Content-Type':'application/xml; charset=utf-8'}});
    return json({error:'API introuvable.'},404);
  } catch(error) { console.error(error); return json({error:error.message==='JSON invalide'?'Requête invalide.':'Une erreur interne est survenue.'},error.message==='JSON invalide'?400:500); }
}
export const config = { path:['/api/*','/robots.txt','/sitemap.xml'] };
